App\VO\ClienteVO:
  exclusion_policy: ALL
    properties:
      id:
        type: integer
      nome:
        type: string
      email:
        type: string
      telefone:
        type: string
      endereco:
        type: App\VO\EnderecoVO
      pedido:
        type: App\VO\PedidoVO