App\Domain\VO\ProdutoVO:
  exclusion_policy: ALL
    properties:
      id:
        type: integer
      nome:
        type: string
      preco:
        type: float
      pedido:
        type: App\Domain\VO\Pedido
