App\Domain\VO\UsuarioVO:
  exclusion_policy: ALL
    properties:
      id:
        type: integer
      nome:
        type: string
      email:
        type: string
      password:
        type: string
      role:
        type: string
      telefone:
        type: string
      endereco:
        type: App\VO\EnderecoVO