App\Domain\VO\PedidoVO:
  properties:
    usuario:
      - NotNull: ~
      - NotBlank: ~
      - Type: integer
    statusPedido:
      - NotNull: ~
      - NotBlank: ~
      - Type: string
    produtos:
      - NotNull: ~
      - NotBlank: ~
      - Type: Doctrine\Common\Collections\ArrayCollection