App\Domain\VO\UsuarioVO:
  properties:
    nome:
      - NotBlank: ~
      - NotNull: ~
      - Type: string
    email:
      - NotBlank: { message: 'Este campo não pode ser vazio' }
      - NotNull: ~
      - Email: { message: 'Email não válido' }
      - App\Infrastructure\Validator\Constraint\Email\ConstraintEmailExistente: ~
      - Type: string
    telefone:
      - NotBlank: { message: 'Este campo não pode ser vazio' }
      - App\Infrastructure\Validator\Constraint\Telefone\ConstraintTelefoneExistente: ~
      - Type: string
    endereco:
      - NotBlank: { message: 'Informe o endereço' }
      - NotNull: ~
      - Type: App\VO\EnderecoVO
    password:
      - NotBlank: { message: 'Password é obrigatório' }
      - NotNull: ~
      - Type: string
